sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 7.0
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

addons:
  hosts:
    - wordpress.dev

script: phpunit --verbose

before_script:
  - composer install
  - bash ./scripts/install.sh
