sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 7.0
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

addons:
  hosts:
    - wordpress.dev

before_script:
  # Version
  - php --version
  - mysql --version

  # Use cURL to fetch WP-CLI
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

  # Make sure WP-CLI is executable
  - chmod +x wp-cli.phar

  # Check if WP-CLI works
  - php wp-cli.phar --info

  # Download WordPress into `wordpress` directory
  - ./wp-cli.phar core download --allow-root --path=wordpress

  # Create wp-config.php
  - ./wp-cli.phar core config

  - cat wordpress/wp-config.php
