sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 7.0
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

addons:
  hosts:
    - wordpress.dev

before_script:
  # Download WP-CLI
  - wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

  # Make sure WP-CLI is executable
  - chmod +x wp-cli.phar

  # Check if WP-CLI works
  - php wp-cli.phar --info

  # Download WordPress into `wordpress` directory
  - ./wp-cli.phar core download

  # Create wp-config.php
  - ./wp-cli.phar core config

  # Create database
  - ./wp-cli.phar db create

  # Install WordPress
  - ./wp-cli.phar core install

  # Start server
  - php -S 0.0.0.0:8080 -t wordpress
