sudo: false

language: php

php:
  - nightly
  - hhvm
  - 5.5
  - 5.4
  - 5.3
  - 5.2

addons:
  hosts:
    - wordpress.dev

before_script:
  # Use cURL to fetch WP-CLI
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

  # Check if WP-CLI works
  - php wp-cli.phar --info

  # Download WordPress into `wordpress` directory
  - ./wp-cli.phar core download --allow-root --path=wordpress
